### PR TITLE
Update recipe for v2.3.1

### PR DESCRIPTION
**Pull request by bskinn**
Switch to pull sdist from PyPI CDN

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] (N/A) Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bskinn** [comment]
@conda-forge-admin, please rerender

**Comment by bskinn** [comment]
The required license files are correctly specified in the recipe. How do I confirm that they are being correctly packaged?

**Comment by anjos** [comment]
The way to do this locally would be to build from a directory instead of the source packages.  For this, you'd have to replace the `url` and `sha256` parts in the `source` section of the conda recipe with `path`, where `path` points to a untarred version of the source tarball (c.f. https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#source-section).  Then, you can execute `build-locally.sh` (or the such from the sphobjinv-feedstock repository).  If everything runs according to plan, a tarballed conda-package will be generated at the `conda-bld/noarch` subdirectory of the base conda prefix (where the `conda` executable sits).  Explore that tarball to check if everything is packaged as you think it should.

**Comment by anjos** [comment]
That said, I'm not sure why the automatic checks are not running for this PR...

**Comment by anjos** [comment]
@conda-forge-admin, please restart ci

**Comment by anjos** [comment]
I re-triggered the CI.  Let's wait for the build results.  I wonder if there are any artifacts preserved with PRs...  This would allow one to check those things without locally building.

**Comment by anjos** [comment]
@bskinn, the tests are passing. Thanks!

I'll leave it to your discretion to merge the PR.  Please note that the conda-forge bot, from now on, should automatically create PRs to update this package.  It may take a few hours after you release the package on PyPI for the bot to react, but it typically works w/o issues.  Maintaining this repo should come with a small overhead.

**Review by anjos — APPROVED** [review]

**Comment by bskinn** [comment]
> bskinn, the tests are passing. Thanks!

How do I see the results of the tests? None of the Actions runs seem like they're running tests.

> Please note that the conda-forge bot, from now on, should automatically create PRs to update this package. It may take a few hours after you release the package on PyPI for the bot to react, but it typically works w/o issues.

Yeah, for future releases I'll let the bot do its thing. I wanted to handle this one manually both so I could have the experience of it, but also because of the switch from pulling from GH to pulling from the PyPI CDN.

**Comment by anjos** [comment]
@bskinn: have you checked [the azure builds for Linux-64](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=620132&view=logs&jobId=656edd35-690f-5c53-9ba3-09c10d0bea97&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d)?  The test suite is being run there (I just double-checked).

**Comment by anjos** [comment]
You must click on the box below with all the "green" (round) flags.  There you will find "All checks have passed".  If you click on "Show all checks", you will have access to links for individual things that were checked with the package.  Choose the linux-64 one and then navigate until you find the link above.

**Comment by anjos** [comment]
A second way: click on the "Checks" tab in this PR and then do the same :-)

**Comment by bskinn** [comment]
Sigh. No, I was only looking at the Actions view for the overall repo. I totally scanned right past that there were checks on the PR, *despite* having looked closely at at least one Azure Pipelines YAML file in the course of this process.

Silly oversight, I figured it was obvious and I was just really missing it. 😅

**Comment by bskinn** [comment]
@anjos -- I'm trying the local build, but I've got something configured wrong. I extracted the 2.3.1 tarball into a working dir, and revised `meta.yml` to the following (`...` is the anonymized first part of the absolute path):

```yaml
source:
#  url: https://github.com/bskinn/sphobjinv/archive/refs/tags/v{{ version }}.tar.gz
#  sha256: 29c2287afe54682bdc6ff66337c36af7dda63b1198166bae7aa0185012e46dde
  path: .../soitest/sphobjinv-2.3.1
```

This is the error I'm getting:

```bash
OSError: Failed to copy .../soitest/sphobjinv-2.3.1 to /home/conda/feedstock_root/build_artifacts/sphobjinv_1669821646767/work/sphobjinv-2.3.1.  Error was: Command 'cp -a .../soitest/sphobjinv-2.3.1 /home/conda/feedstock_root/build_artifacts/sphobjinv_1669821646767/work/sphobjinv-2.3.1' returned non-zero exit status 1.
```

It also doesn't work to just point at the still-packed tarball; same error. Do I have something set up wrong with my Docker or something? It looks like it's trying to copy the extracted source directory from the local drive into the Docker container/instance/whatever... and maybe Docker isn't set up to reach out to the actual filesystem?

**Comment by bskinn** [comment]
All that said, the `.conda` file that's live on conda-forge *does* have both license files in it, so we're all good there.

**Comment by anjos** [comment]
OK, why is the path starting with 3 dots?  That looks suspicious.

The path should be relative to the recipe directory (ie. the `meta.yaml` file).  To test if everything is detected correctly, just move the directory to the same level as the recipe, then use something like `path: sphobjinv-2.3.1`.  It should work.

**Comment by bskinn** [comment]
It's not *actually* starting with three dots. It's actually `/home/{username}/soitest/sphobjinv-2.3.1`. I should have anonymized it this way instead, less confusing.

Your fix makes sense -- pulling the unpacked source tree inside the recipe working folder should make it get pulled into Docker and then be visible. I'll give that a shot.

I saw in the instructions that it said, "relative to the [whatever]", but I assumed an absolute path would work as well. Makes sense that it doesn't, in retrospect.

**Comment by bskinn** [comment]
Yup, built fine once I pulled the unpacked sdist into `recipe`.

Cool, thanks again @anjos!!

**Comment by anjos** [comment]
Thank **you** for all the hard work maintaining the upstream and, now, also this package!  Excellent job!

**Pull request merged**
